# Generated by Django 4.2.3 on 2023-08-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodquery',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
