# Generated by Django 4.2.3 on 2023-08-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_bot_app', '0002_alter_foodquery_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersFoodQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('query', models.CharField(max_length=255)),
                ('calories', models.FloatField()),
            ],
        ),
    ]
